### ISSUE TITLE
Add warning about different sdl2 packages

### ISSUE THREAD

**Issue by EriKWDev** [ftsf/nico#67] opened 2021-07-09 20:42 UTC
I was following the beginners tutorial but I was having trouble compiling the initial nicoboot example app that was created for me but I couldn't figure out why. It said it couldn't load `sdl2/sdl` even though I'd installed nico, its dependencies and added SDL2.dll to the root folder.

I later figured out I had other nimble sdl2 packages installed (I think it was just called sdl2), while nico needs `sdl2_nim` specifically it appears. After uninstalling the old sdl2 packages using nimble it worked fine again.

Is there a warning somewhere about this or did I just miss it? Maybe it should be added to the README if not already there.

**Comment by ftsf** [comment] 2021-07-10 02:41
it uses `sdl2_nim` which is listed as a nimble dependency in `nico.nimble` so it should get automatically installed when you run `nimble install nico`

the SDL2.dll is a runtime dependency and isn't required to build, but is required for running on Windows, on other platforms libSDL2.so would be required instead.

Can you please let me know the exact error message you were getting?

**Comment by EriKWDev** [comment] 2021-07-14 16:36
I had other sdl2 nimble packages installed before I installed nico which was the problem. They seem to be imported in the same way since they all have the same name.

```yaml
> nimble rund
<personal path>nico-0.4.0\nico\controller.nim(2, 14) Error: cannot open file: sdl2/sdl

Error: Exception raised during nimble script execution
```

I cannot quire reproduce the exact same, but the simplest way is to `nimble uninstall sdl2` (which uninstall both sdl2 and sdl2_nim) and then `nimble install sdl2` (not sdl2_nim...). And then trying to run the prject produces the above error.
Obviously having the wrong dependency installed causes an error, but I was in a position where I had both (or even more?) sdl2-packages installed and it threw the same error.

Don't know if a warning is warranted in the README or what would be the solution to inform users that the correct sdl2 package should be the only one installed...

**Comment by SolitudeSF** [comment] 2021-07-14 18:41
it doesnt matter if both of them are installed when you are building with nimble, since nimble will only supply needed packages to the compiler. also they are imported differently and cant conflict.

**Comment by EriKWDev** [comment] 2021-07-14 18:44
Well, I wouldn't have opened this issue unless I experienced one. I'm not saying I know why it happened, just trying my best to recreate it :/

**Comment by ftsf** [comment] 2021-07-28 04:38
I'm going to close this issue if there's no way to reproduce it. If anything it may be a bug with nimble if it's uninstalling packages other than what you're telling it to uninstall.

**Closed by ftsf** 2021-07-28 04:38 UTC
