### ISSUE TITLE
Volume Control Still doesnt work.

### ISSUE THREAD

**Issue by beef331** [ftsf/nico#19] opened 2020-06-08 02:19 UTC
Issue #18 still is a problem and just bumping it since you closed it and have not responded since. On my system 1-255 is at 100% volume and 0 is at 0% volume. This was an issue across two Ubuntu derived OS systems.

**Comment by ftsf** [comment] 2020-06-08 03:09
closing as duplicate of #18, reopened #18

**Closed by ftsf** 2020-06-08 03:09 UTC
