### ISSUE TITLE
Audio bug w/js - Music not playing, infinite sfx

### ISSUE THREAD

**Issue by avahe-kellenberger** [ftsf/nico#28] opened 2020-07-09 20:50 UTC
When compiling [this project](https://github.com/crab-dev/snake) for the web, the music is not played, and the ending sound effect (when you die) is played infinitely and the game doesn't progress. This could be some other compilation related bug, that doesn't have to do with audio.

Try the game locally first to see how it should behave, because it works natively.

**Comment by ftsf** [comment] 2020-07-10 01:38
This is two separate issues, 

1. Music not playing on start on JS backend, this is a platform limitation for WebAudio to stop it autoplaying on start.
It can be solved but It will require changes per game, perhaps triggering music playing after pressing a button on the title screen for example. It's not something we can really solve generically in nico without obtrusive changes, so I think the best solve is documentation.

2. The issue is caused by a bug in `music(channel, -1)` which is fixed by @beef331's PR https://github.com/ftsf/nico/pull/29 thanks!

**Closed** 2020-09-29 04:07 UTC
Labels: JS
