### ISSUE TITLE
new error when trying to build platformer.nim on Nim 1.2.0 with latest source

### ISSUE THREAD

**Issue by UNIcodeX** [ftsf/nico#17] opened 2020-04-20 16:29 UTC
```
nim --version
Nim Compiler Version 1.2.0 [Windows: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 7e83adff84be5d0c401a213eccb61e321a3fb1ff
active boot switches: -d:release
```

```
git clone https://github.com/ftsf/nico.git
Cloning into 'nico'...
remote: Enumerating objects: 133, done.
remote: Counting objects: 100% (133/133), done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 703 (delta 83), reused 109 (delta 64), pack-reused 570
Receiving objects: 100% (703/703), 386.35 KiB | 1.54 MiB/s, done.
Resolving deltas: 100% (418/418), done.
```

```
# cd nico/examples
# nim c -r -d:release platformer.nim
Hint: used config file 'C:\Users\unicodex\.choosenim\toolchains\nim-1.2.0\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: platformer [Processing]
Hint: nico [Processing]
Hint: common [Processing]
Hint: math [Processing]
Hint: bitops [Processing]
Hint: macros [Processing]
Hint: tables [Processing]
Hint: hashes [Processing]
Hint: algorithm [Processing]
Hint: unicode [Processing]
Hint: times [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: options [Processing]
Hint: typetraits [Processing]
Hint: winlean [Processing]
Hint: dynlib [Processing]
Hint: time_t [Processing]
Hint: keycodes [Processing]
Hint: controller [Processing]
Hint: sdl [Processing]
Hint: ringbuffer [Processing]
Hint: unittest [Processing]
Hint: streams [Processing]
Hint: sets [Processing]
Hint: sequtils [Processing]
Hint: os [Processing]
Hint: pathnorm [Processing]
Hint: osseps [Processing]
Hint: terminal [Processing]
Hint: strformat [Processing]
Hint: colors [Processing]
C:\Users\unicodex\.nimble\pkgs\nico-0.2.0\nico\backends\common.nim(140, 3) Hint: 'LineIterator' is declared but not used [XDeclaredButNotUsed]
C:\Users\unicodex\.nimble\pkgs\nico-0.2.0\nico\backends\common.nim(141, 3) Hint: 'Edge' is declared but not used [XDeclaredButNotUsed]
C:\Users\unicodex\.nimble\pkgs\nico-0.2.0\nico\backends\common.nim(7, 8) Warning: imported and not used: 'strutils' [UnusedImport]
Hint: sdl2 [Processing]
Hint: json [Processing]
Hint: lexbase [Processing]
Hint: parsejson [Processing]
Hint: nimPNG [Processing]
Hint: endians [Processing]
Hint: buffer [Processing]
Hint: nimz [Processing]
Hint: filters [Processing]
Hint: osproc [Processing]
Hint: strtabs [Processing]
Hint: cpuinfo [Processing]
Hint: ospaths [Processing]
C:\Users\unicodex\.nimble\pkgs\nico-0.2.0\nico\backends\sdl2.nim(34, 8) Warning: import os.nim instead; ospaths is deprecated [Deprecated]
Hint: parsecfg [Processing]
Hint: sndfile [Processing]
Hint: random [Processing]
C:\Users\unicodex\.nimble\pkgs\nico-0.2.0\nico\backends\sdl2.nim(333, 50) Warning: use `csize_t` instead; csize is deprecated [Deprecated]
C:\Users\unicodex\.nimble\pkgs\nico-0.2.0\nico\backends\sdl2.nim(333, 19) Error: type mismatch: got <ptr RWops, ptr uint8, int literal(1), csize>
but expected one of:
proc rwRead(context: ptr RWops; p: pointer; size: csize_t; maxnum: csize_t): csize_t
  first type mismatch at position: 4
  required type for maxnum: csize_t
  but expression 'csize(1)' is of type: csize

expression: rwRead(fp, addr(buffer[offset]), 1, csize(1))
```

**Comment by krisppurg** [comment] 2020-04-20 20:53
I haven't tried this, but I think maybe doing `nimble install nico` will help since there were commits that may be unstable after bumping version up.

**Comment by UNIcodeX** [comment] 2020-04-20 21:02
I completely hosed my nimble packages, Nim compiler and everything, then
reinstalled from scratch, including `nimble install nico` and this is the
error I got.

**Comment by krisppurg** [comment] 2020-04-21 08:02
I'll investigate this issue soon or later on and try to look for a solution.

**Comment by ftsf** [comment] 2020-04-22 08:24
Hi, I'll look into this, I was using Nim 1.0.2, I'll upgrade to 1.2 and try to fix any issues.

**Comment by ftsf** [comment] 2020-04-22 08:56
I was able to reproduce this issue with a fresh `.nimble`, I've pushed a fix. Let me know if you're still having problems.

**Closed** 2020-04-22 08:56 UTC

**Comment by UNIcodeX** [comment] 2020-04-22 17:31
All of the examples work now! Even on windows after installing SDL2 and libsndfile on Windows with scoop.

You're awesome, my friend. Thank you for your dedication.
