### ISSUE TITLE
Colors are rendered incorrectly

### ISSUE THREAD

**Issue by moigagoo** [ftsf/nico#52] opened 2021-03-04 19:53 UTC
Hi!

I've created a spritesheet in Gimp, using this palette: https://lospec.com/palette-list/pico-8

The spritesheet: https://imgur.com/36iND5H

The problem is the sprites from it are rendered in different colors: https://imgur.com/na9JSC1

Why is that? I've tried adding explicit `setPalette(loadPalettePico8())`, that didn't change anything. Tried `setPalette(loadPaletteFromGPL("pico-8.gpl"))`, and the entire screen is just black.

P.S. Nico is fantastic! Thank you so much for the amazing work you do. I’ve just created my first game from scratch, without any prior experience, in just five hours total. And it’s been pure fun all the way.

**Comment by moigagoo** [comment] 2021-03-04 20:12
When built for web, the colors are correct.

**Comment by ftsf** [comment] 2021-03-05 02:27
The problem is that the spritesheet you shared is not using the correct palette. It's removed all the unused palette entries and reordered them.
![image](https://user-images.githubusercontent.com/141492/110057974-a2dee000-7db5-11eb-9124-613cddca27ca.png)
This may be an issue with how gimp saves images.
You might want to uncheck this option when converting to Indexed
![image](https://user-images.githubusercontent.com/141492/110058499-842d1900-7db6-11eb-9085-1ab0072e8381.png)

It should be using this palette:
![image](https://user-images.githubusercontent.com/141492/110058125-eb969900-7db5-11eb-8bf6-b14c337eb4ed.png)

The palette indices are important, though less so on the web-backend since we don't have access to the underlying indices when loading an image via web we have to map each pixel to the closest palette color.

**Comment by moigagoo** [comment] 2021-03-05 06:27
> It should be using this palette:

How do I get it for GIMP? I see you're using this editor, Aseprite, but I don't think I'm ready to buy it yet. So, if there's a way to create spritesheets with GIMP, I'd be happy to learn.

**Comment by ftsf** [comment] 2021-03-05 06:35
In GIMP when converting from RGB to Indexed mode (Image -> Mode -> Indexed...), select the desired palette you'll be using in Nico and disable the checkbox "Remove unused and duplicate colors from colormap".

**Comment by moigagoo** [comment] 2021-03-05 06:37
> In GIMP when converting from RGB to Indexed mode (Image -> Mode -> Indexed...), select the desired palette you'll be using in Nico and disable the checkbox "Remove unused and duplicate colors from colormap".

Yeah, that's what I'm doing:

![image](https://user-images.githubusercontent.com/1045340/110076903-b0d53680-7d9e-11eb-83f7-53a774163463.png)

Then, during PNG export, I'm using the default settings:

![image](https://user-images.githubusercontent.com/1045340/110076955-c64a6080-7d9e-11eb-9a42-c4f6e3c89830.png)

**Comment by ftsf** [comment] 2021-03-05 07:09
It seems there's a related issue with gimp's exporting of paletted PNGs. https://gitlab.gnome.org/GNOME/gimp/-/issues/1256
Another one related to loading them https://gitlab.gnome.org/GNOME/gimp/-/issues/414

![image](https://user-images.githubusercontent.com/141492/110078914-83a77900-7ddc-11eb-9ec9-a158a8b798a4.png)

This issue has been around for at least 3 years so I wouldn't expect it to get fixed in a rush. It might be worth looking for another pixel art program.

**Comment by moigagoo** [comment] 2021-03-05 07:13
Thanks a lot for your help 🙏

**Comment by moigagoo** [comment] 2021-03-06 17:44
@ftsf Sorry to dump an old issue, but I'm really stuck with those spritesheets. Maybe, you could recommend a sprite editor that's capable of produce indexed 8-bit PNGs with embedded palettes?

I've tried GIMP, Krita, Paint.NET, Piskel, and a bunch of other online editors so far, with little success.

**Comment by ftsf** [comment] 2021-03-08 03:04
I think I'll adjust it so if you feed Nico an RGBA image it'll load it as it does in the web version by matching colours in the image to colours in the palette which should allow you to use any image editor.

**Comment by moigagoo** [comment] 2021-03-08 11:58
Oh man, you’re awesome, thank you.

Is there anything I can help with? I couldn’t find the specific place in the code that needs modification but if you point me to it and outline the necessary changes, I’ll be happy to send a PR.

**Comment by ftsf** [comment] 2021-03-08 12:20
@moigagoo There's actually already a PR for this https://github.com/ftsf/nico/pull/34

I haven't merged it yet, as I'd like for it to only happen when it's an RGBA image, but you can use that change for now, in the future I plan for it to treat paletted pngs as they work now, but RGBA pngs will be matched to their nearest palette entries like in that PR.

**Comment by ftsf** [comment] 2021-09-01 03:26
palette loading should be much more reliable now, if you encounter any more issues with palette loading via GPL or image please let me know and i'll add them as test cases.

**Closed by ftsf** 2021-09-01 03:26 UTC
